const ropas = [
    {
        genero: "hombre",
        tipo: "polera",
        color: "negra",
        manga: "larga",
        Material: "algodon",
        valor: "15.000",
    },
    {
        genero: "mujer",
        tipo: "polera",
        color: "roja",
        manga: "corta",
        Material: "algodon",
        valor: "15.000",
    },
    {
        genero: "mujer",
        tipo: "polera",
        color: "blanca",
        manga: "corta",
        Material: "algodon",
        valor: "15.000",
    },
    {
        genero: "hombre",
        tipo: "polera",
        color: "blanca",
        manga: "corta",
        Material: "algodon",
        valor: "15.000",
    },
    {
        genero: "niño unisex",
        tipo: "polera",
        color: "blanca",
        manga: "corta",
        Material: "algodon",
        valor: "12.000",
    },
    {
        genero: "niño unisex",
        tipo: "polera",
        color: "negra",
        manga: "larga",
        Material: "algodon",
        valor: "12.000",
    },
    {
        genero: "niño unisex",
        tipo: "poleron",
        color: "negra",
        manga: "larga",
        Material: "algodon, spandex",
        valor: "20.000",

    },
    {
        genero: "hombre",
        tipo: "poleron",
        color: "azul",
        manga: "larga",
        material: "algodon",
        valor: "30.000",
    },
    {
        genero: "mujer",
        tipo: "poleron",
        color: "azul",
        manga: "larga",
        material: "algodon",
        valor: "30.000",
    },
    {
        genero: "mujer",
        tipo: "poleron",
        color: "negro",
        manga: "larga",
        material: "algodon",
        valor: "30.000",
    },
    {
        genero: "hombre",
        tipo: "poleron",
        color: "blanco",
        manga: "larga",
        material: "algodon",
        valor: "30.000",
    },
    {
        genero: "hombre",
        tipo: "poleron",
        color: "rojo",
        manga: "larga",
        material: "algodon",
        valor: "30.000",
    },
    {
        genero: "hombre",
        tipo: "poleron",
        color: "negro",
        manga: "larga",
        material: "algodon",
        valor: "30.000",
    },
    {
        genero: "niño unisex",
        tipo: "poleron",
        color: "blanco",
        manga: "larga",
        Material: "algodon, spandex",
        valor: "20.000",
    },
    {
        genero: "hombre",
        tipo: "chaqueta",
        color: "negro",
        manga: "larga",
        Material: "cuero",
        valor: "45.000",
    },  {
        genero: "mujer",
        tipo: "chaqueta",
        color: "rojo",
        manga: "larga",
        Material: "cuero",
        valor: "45.000",
    },  {
        genero: "hombre",
        tipo: "chaqueta",
        color: "azul",
        manga: "sin mangas",
        material: "jeans",
        valor: "40.000",
    },
    {
        genero: "hombre",
        tipo: "chaqueta",
        color: "cafe",
        manga: "larga",
        material: "cuero",
        valor: "40.000",
    },
    {
        genero: "hombre",
        tipo: "chaqueta",
        color: "negra",
        manga: "sin mangas",
        material: "jeans",
        valor: "40.000",
    },
    {
        genero: "niño unisex",
        tipo: "chaqueta",
        color: "rojo",
        manga: "larga",
        Material: "algodon",
        valor: "35.000",
    },
    {
        genero: "niño unisex",
        tipo: "chaqueta",
        color: "verde",
        manga: "corta",
        Material: "algodon",
        valor: "35.000",
    },
    {
        genero: "niño unisex",
        tipo: "poleron",
        color: "rojo",
        manga: "larga",
        Material: "algodon",
        valor: "30.000",
    },
    {
        genero: "mujer",
        tipo: "chaqueta",
        color: "beige",
        manga: "larga",
        Material: "algodon",
        valor: "35.000",
    },
    {
        genero: "mujer",
        tipo: "chaqueta",
        color: "negra",
        manga: "larga",
        Material: "algodon",
        valor: "35.000",
    },
    {
        genero: "niño unisex",
        tipo: "polera",
        color: "rojo",
        manga: "larga",
        Material: "algodon",
        valor: "35.000",
    },
    {
        genero: "mujer",
        tipo: "poleron",
        color: "verde",
        manga: "larga",
        Material: "algodon",
        valor: "35.000",
    },
    {
        genero: "mujer",
        tipo: "chaqueta",
        color: "marron",
        manga: "larga",
        Material: "cuero",
        valor: "45.000",
    }, 
];

